<div class="modal fade" id="toc_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-modal="true">
	<div class="modal-dialog modal-xl">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">TERMS OF USE</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">
				
<p><b>TERMS OF USE</b></p><br>

<p>Welcome to <b>QC eServices</b>!</p>

<p style="text-indent: 50px;" align="justify">This e-Services Agreement (“Agreement”) is a legal agreement for the use of the software systems for the input, monitoring, validation, processing, and analytics of data (“Services”) between QC eServices (“us”, our”, or “we”) and the entity or person (“you”, “your”, or “user”) who registered on the QC eServices Sign-up Page. This Agreement describes the terms and conditions that apply to your use of the Services.</p>

<p style="text-indent: 50px;" align="justify">If you do not understand any of the terms of this Agreement, please contact us at <b><i>eservices@quezoncity.gov.ph</i></b>.
You may not access or use any of the e-Services unless you agree to abide by all of the terms and conditions in this Agreement.</p><br><br>
<b>OVERVIEW OF THIS AGREEMENT</b><br>
<p>This Agreement provides a general description of the e-Services that the user is availing of.</p>
<p>SECTION A GENERAL TERMS: Registration and using your Account.</p>
<p>SECTION B TECHNOLOGY:</p>
<p>SECTION C PAYMENT TERMS AND CONDITIONS:</p>
<p>SECTION D DATA USAGE, PRIVACY AND SECURITY</p>
<p>SECTION E ADDITIONAL LEGAL TERMS</p><br>

<p><b>SECTION A: GENERAL TERMS</b></p><br>
<p style="font-weight: bold;">1. Your Account</p>
<p style="text-indent: 50px;" align="justify">Before using the Services, you must create an account (“Account”). To register for an Account, you or the person or people submitting the application on your behalf ( “Representative”) must provide us with your business or trade name, address, contact person, email, phone number, business and/or tax identification number, the nature of your business or activities about you that we require.</p>
<p style="text-indent: 50px;" align="justify">Upon submission of the complete registration requirements, your application will be reviewed, and the e-Services will be available to you upon our approval. Application request review and approval takes at least two (2) business days. We reserve the right to deny or reject application requests.</p>

<p style="text-indent: 50px;" align="justify">Registration and Permitted Activities: Only businesses (including sole proprietors), and other entities or institutions based in the Quezon City, Philippines are eligible to apply for an Account to use the e-Services described in this Agreement.</p>
<p style="text-indent: 50px;" align="justify">Business Representative: You shall affirm that your Representative is duly authorized to provide the information described in Section A.1.a hereof on your behalf and to bind you to this Agreement. We may require you or your Representative to provide additional information or documentation demonstrating your Representative’s authority.</p>
<p style="text-indent: 50px;" align="justify">If you are a sole proprietor, you will also affirm that your representative shall be personally responsible and liable for your use of the e-Services registered under your account, including payment of any amounts owed under this Agreement.</p>
<p>Validation and Underwriting: At any time during the term of this Agreement and your use of the e-Services, we may require additional information from you to verify beneficial ownership or control of the business, validate information you provided, verify you and your Representative’s identity, if you have one. This additional information may include business invoices, copies of government-issued identification, business licenses, or other information related to your business, its beneficial owners or principals.</p><br>

<p style="font-weight: bold;">2. SERVICES AND SUPPORT</p>
<p style="text-indent: 50px;" align="justify">We will provide you with support to resolve general issues relating to your Account and issues that prevent you to properly use the e-Services as intended (“System Errors”). This support includes resources and documentation that we make available to you through our Ticketing System in-App and on our website (collectively, “Documentation”). If you still have questions after reviewing the Documentation, please contact us at <b><i>eservices@quezoncity.gov.ph</i></b>.</p><br>

<p style="font-weight: bold;">3. e-SERVICE REQUIREMENTS, LIMITATIONS AND RESTRICTIONS</p>
<p style="text-indent: 50px;" align="justify">In compliance with applicable laws, You must use the e-Services in a lawful manner, and must obey all laws, rules, and regulations (collectively, “Laws”) applicable to your use of the e-Services and 'Foodpack inquiry search / Kalingang QC' and other features (collectively, “Transactions”). This may include compliance with domestic and international laws related to the use or provision of data collation and collection services, notification and consumer protection, unfair competition, privacy, and false advertising, and any other laws relevant to business transactions.</p><br>

<p>OTHER RESTRICTED ACTIVITIES: You may not use the e-Services to facilitate illegal transactions or to permit others to use the e-Services for personal, family or household purposes. In addition, you may not allow, and may not allow others to:</p>
<p style="text-indent: 50px;">a)	Access or attempt to access non-public systems, programs, data, or services;</p>
<p style="text-indent: 50px;">b)	Copy, reproduce, republish, upload, post, transmit, resell, or distribute in any way, any data, content, or any part of the Services, Documentation, or our mobile device application and website except as expressly permitted by applicable laws;</p>
<p style="text-indent: 50px;">c)	Utilize the Service to use, transfer, view, circulate, upload, access any and all forms of data you do not own or do not have documented permission and rights of its use from their respective owners;</p>
<p style="text-indent: 50px;">d)	Act as service bureau or pass-through agent for the e-Services;</p>
<p style="text-indent: 50px;">e)	Transfer any rights granted to you under this Agreement;</p>
<p style="text-indent: 50px;">f)	Work around any of the technical limitations of the Services or enable functionality that is disabled or prohibited;</p>
<p style="text-indent: 50px;">g)	Reverse engineer or attempt to reverse engineer the Services except as expressly permitted by Laws;</p>
<p style="text-indent: 50px;">h)	perform or attempt to perform any actions that would interfere with the normal operation of the Services or affect use of the Services by our other users; or</p>
<p style="text-indent: 50px;">i)	impose an unreasonable or disproportionately large load on the e-Service.</p><br>
<p style="font-weight: bold;">4. DISCLOSURES AND NOTICES; ELECTRONIC SIGNATURE CONSENT</p>
<p style="text-indent: 50px;" align="justify">Consent to Electronic Disclosures and Notices: By registering for an account, you agree that such registration constitutes your electronic signature, and you consent to the electronic provision of all disclosures and notices from us including those required by law. You also agree that your electronic signature will have the same legal effect as a physical signature.	
Methods of Delivery: You agree that we can provide notices about the e-Services to you through our website or by email or text messages to your registered and authorized contact details. Notices may include notifications about your account, changes to the e-Services, or other information we are required to provide to you. You also agree that electronic delivery of a notice has the same legal effect as if have been provided with a physical copy of the same. We will consider that the notice has been received by you within 24 hours from the time the notice was either posted to our website or emailed to you. We shall not liable for your non-receipt of notices due to network outage, power outage, device loss, device incompatibility, incorrect contact details provided, network and/or firewall restrictions, and other issues which are beyond our control.
Text Messages: You authorize us to provide you notices via text message to allow us to verify you or your representative’s control over your account (such as through two-step verification), and to provide you with other critical information about your account. Standard text or data charges may apply to such notices. Where offered, you may disable text message notifications by responding to any such message with “STOP”, or by following instructions provided in the message. However, by disabling text messaging, you may be disabling important security controls (as defined below) on your account and may increase the risk of loss to your business.</p>
<p>Requirements for Delivery: It should come as no surprise to you that you will need a computer or mobile device, internet connectivity, and an updated web browser to access the e-Services and review the notices provided to you.</p><br>

<p>Withdrawing Consent: Due to the nature of the e-Services, you will not be able to begin using the e-Services without agreeing to electronic delivery of notices. However, you may choose to withdraw your consent to receive notices electronically by terminating your Account.</p><br>
<p style="font-weight: bold;">5. TERMINATION</p>
<p style="text-indent: 50px;" align="justify">Term and Termination: This agreement is effective upon registration and continues until terminated by us, you, or your representative. You may terminate this agreement at any time by sending us an email with your request to terminate and close your account. Your account will be terminated within 120 business days from the receipt of such request. We may terminate this agreement or close your account at any time for any reason by providing you a notice. We may suspend your account or terminate this agreement, if:</p>
<p style="text-indent: 30px;">a)	We determine in our sole discretion that you are ineligible for the e-Services because of significant fraud or credit risk, or any other risks associated with your account;</p>
<p style="text-indent: 30px;">b)	you used the e-Services in a prohibited manner or otherwise do not comply with any of the provisions of this agreement;</p>
<p style="text-indent: 30px;">c)	Any Law, requires us to do so; or</p>
<p style="text-indent: 30px;">d)	Whatever manner we are otherwise entitled to do so under this agreement.
In addition, upon termination of this Agreement, you understand and agree that:</p>
<p style="text-indent: 30px;">a)	all licenses granted to you by this agreement will be terminated;</p>
<p style="text-indent: 30px;">b)	We reserve the right but have no obligation to delete all of your information and account data stored on our servers;</p>
<p style="text-indent: 30px;">c)	We will not be liable to you for compensation, reimbursement, or damages related to your use of the e-	Services, or any termination or suspension of the Services or deletion of your information or account data; and</p>
<p style="text-indent: 30px;">d)	You shall still be liable to us for any fees or fines, or other financial obligation incurred by you or through your use of the services prior to its termination.</p><br><br>
<p><b>SECTION B: TECHNOLOGY</b></p><br>
<p style="font-weight: bold;">1. Web System and Mobile Application</p>
<p style="text-indent: 50px;" align="justify">We develop and provide access to the web system and/or mobile application that may be used to access the e-Services. You may use the them solely as described in the documentation provided to you using your account.</p>
<p style="text-indent: 50px;" align="justify">You may not use the web system and/or mobile application for any purpose, function, or feature not described in the documentation or otherwise communicated to you by us. Due to the nature of the e-Services, we will update the Documentation from time to time, and may add or remove functionalities with or without notice to you. We will provide you a notice in the event of material changes, deprecations, or removal of functionalities through text message or e-mail so that you may continue using the e-Services with minimal interruption.</p><br>

<p style="font-weight: bold;">2. Ownership of Intellectual Property (IP) Rights</p>
<p style="text-indent: 50px;" align="justify">You shall own all of your master data, transactional raw data captured, and output reports gathered, processed, and generated from the web system and mobile application. We exclusively own all rights, titles, interests in the patents, copyrights (including rights in derivative works), moral rights, rights of publicity, trademarks or service marks, logos and designs, trade secrets, and other intellectual property embodied by, or contained in the web system, mobile application, services, dashboard and report designs, system designs, and documentation (collectively, “QC eServices IP”) or any copies thereof. QC eServices IP is protected by copyright, trade secret, patent, and other intellectual property Laws, and all rights in QC eServices IP not expressly granted to you in this agreement remains reserved to us.</p>
<p style="text-indent: 50px;" align="justify">You may choose to, or we may invite you to submit comments or ideas about improvements to the e-Service, our web system, our mobile application, our platform, or any other component of our products or services (“Ideas”). If you submit an idea to us, we will presume that your submission was voluntary, and delivered to us without any restrictions on our use of the Idea. You also agree that we have no fiduciary or any other obligation to you in connection with any Idea you submit to us, and that we are free to use your Ideas without any attribution or compensation to you.</p><br>
<p style="font-weight: bold;">3. License coverage</p>
<p style="text-indent: 50px;" align="justify">You are granted a non-exclusive and non-transferable license to electronically access and use the QC eServices IP only in the manner described in this agreement. We shall not sell to you the QC eServices IP, and you do not have the right to sublicense the QC eServices IP. We may make updates to the QC eServices IP and/or services that are available to you. This is automatically and electronically published by us, but we may require action on your part before you may use the updated QC eServices IP and/or Services. This includes mobile application updates, or acceptance of new or additional terms of this Agreement. We may revoke or terminate this license at any time if you use QC eServices IP in a manner prohibited by this Agreement.</p>
<p>You may not:</p>
<p style="text-indent: 30px;">a)	Claim or register ownership of QC eServices IP on your behalf or on behalf of others;</p>
<p style="text-indent: 30px;">b)	Sublicense any rights in QC eServices IP granted by us;</p>
<p style="text-indent: 30px;">c)	Import or export any QC eServices IP to a person or country in violation of any country’s export control Laws; or</p>
<p style="text-indent: 30px;">d)	Use QC eServices IP in a manner that violates this Agreement or Laws.</p><br>
<p style="font-weight: bold;">4. References to Our Relationship</p>
<p style="text-indent: 50px;" align="justify">During the term of this agreement, you may publicly identify us as the provider of the e-Services to you and we may publicly identify you as a client. If you do not want us to identify you as a client, please notify us at <b><i>eservices@quezoncity.gov.ph</i></b>. Both you and I may not imply any untrue endorsement, or affiliation between you and us. Upon termination of your account, both you and I shall remove any public references to the relationship between you and I including any public documentations and materials.</p><br><br>
<p><b>SECTION C:PAYMENT TERMS AND CONDITIONS</b></p><br>
<p style="font-weight: bold;">1. Service Fees</p>
<p style="text-indent: 50px;" align="justify">We will provide the e-Services to you for the fees and rates (“Fees”) described on the QC eServices website. The fees shall include charges for the set-up, access, support, and for other transactions connected with your account such as penalties, special handling fees, and miscellaneous fees. We may revise the fees at any time but shall be notified at least 30 days notice before revisions become applicable to you, or a longer period of notice if this is required by any applicable law.
</p><p style="font-weight: bold;">2. Payment Terms, Methods and Schedule</p>
<p style="text-indent: 50px;" align="justify">Your monthly bill for the upcoming month is automatically generated by the system on the 21st day of the current month and is due after 5 days. This is based on the number of web system and/or mobile application users you registered in your Account (“End-User”) on or before the 20th day of the current month.</p>
<p style="text-indent: 50px;" align="justify">All payments should be settled via our third-party Payment System Provider, PayPal. The Payment Terms may also be amended from time to time and we will provide you with at least 30 days notice before revisions become applicable to you, or a longer period of notice if this is required by applicable Law. Your continuing use of the payment services constitutes your consent and agreement to such additions, removals, and amendments.</p>
<p style="text-indent: 50px;" align="justify">You agree to abide by all of the terms and conditions specified by PayPal in using their services. We shall not liable and responsible for any issues encountered by your use of PayPal services. Should you encounter any issues regarding your PayPal account and payment, please contact the provider immediately.</p>
<p style="font-weight: bold;">3. Taxes and Other Expenses</p>
<p style="text-indent: 50px;" align="justify">Fees are exclusive of any applicable taxes, except as expressly stated to the contrary. You have sole responsibility and liability for remitting taxes for your business to the appropriate tax and revenue authorities in your country.</p>
<p style="font-weight: bold;">4. Payment Processing</p>
<p style="text-indent: 50px;" align="justify">When you register for an account, you may be asked for financial information, or information we may use to identify you, your representative associated with your Account for purposes of payment method and processing. Throughout the term of this agreement, we may share information about your account with a third-party payment systems in order to verify your eligibility to use the said payment processing services with PayPal, establish any necessary accounts or credit with payment method providers, monitor charges and other activity. We are not a bank and we do not accept deposits, provide loans, or extend credit. We do not offer banking or other services regulated by the Bangko Sentral ng Pilipinas.</p>

<p>We reserve the right to reject your application or terminate your Account if you are ineligible for use of PayPal services.</p>
<p style="font-weight: bold;">5. Processing Disputes and Refunds</p>
<p style="text-indent: 50px;" align="justify">You are shall be eesponsible for the reporting of disputes and requests for refunds by emailing us at <b><i>eservices@quezoncity.gov.ph</i></b>. Payment disputes will only be honored and investigated if reported within 60 days from the billing date. We may request for additional information from you to evaluate the disputes and requests for refunds. If substantiated by proof and a refund is warranted, you will be only be issued a credit memo for usage on future billings. If a refund is issued, we will provide you notice and a description of the cause of the reversal.</p><br><br>

<p><b>SECTION D DATA USAGE, PRIVACY AND SECURITY</b></p>
<p style="font-weight: bold;">1. DATA USAGE OVERVIEW</p>
<p style="text-indent: 50px;" align="justify">Protecting, securing, and maintaining the information processed and handled through the e-Services is one of our top priorities, and it should be yours too. This section describes our respective obligations when handling and storing information connected with the e-Services. The following terms used in this section relate to data provided to us by you or other end-users, or received or accessed by you through your use of the e-Services:</p>
<p>'PERSONAL DATA' means any information, whether true or not, that is related to a person, that can be used to specifically identify that person or not, and is transmitted or accessible through the e-Services.</p>
<p>'USER DATA' means any information that describes your business and its operations, your products or services.</p>
<p>'QC eServices DATA' means details of the web system and mobile application transactions over QC eServices infrastructure, information used in fraud detection and analysis, aggregated or anonymized information generated from data collected, and any other information created by or originating from the Services.</p>
<p>The term 'DATA' used without a modifier means all Personal Data, User Data, and QC eServices data.</p>
<p>We process, analyze, and manage data to:</p>
<p style="text-indent: 30px;">a)	Provide e-services to you, other end-Users, and other users of the e-Services;</p>
<p style="text-indent: 30px;">b)	Mitigate fraud, financial loss, or other harm to you, end-Users, and other users of the e-Services; and</p>
<p style="text-indent: 30px;">c)	Analyze, develop, and improve our products, systems, and tools. We do not provide Personal Data to unaffiliated parties for marketing their products to you. You understand and consent to our use of Data for the purposes and in a manner consistent with this Section.</p><br>
<p style="font-weight: bold;">2. DATA PROTECTION AND PRIVACY</p>
<p>Confidentiality: We will only use Data as permitted by this agreement, or as otherwise directed or authorized by you. You will protect all Data you receive through the e-Services, and you cannot disclose or distribute any such Data, and you will only use such Data in conjunction with the e-Services and as permitted by this agreement. Neither party may use any Personal Data to market to other parties unless it has received the express consent to do so.</p>
<p style="text-indent: 50px;" align="justify">We may, however, disclose Data if presented by any legal instruments such as a subpoena, court order, search warrant, or applicable laws.</p>
PRIVACY: You affirm that you are now and will continue to be compliant with all applicable laws governing the privacy, protection, and your use of Data that you provide to us or access through your use of the e-Services. You also affirm that you have obtained all necessary rights and consents under applicable Laws to disclose to us – or allow us to collect, use, retain, and disclose – any Data that you provide to us or authorize us to collect, including Data that we may collect directly from End-Users using cookies or other similar means. As may be required by Law and in connection with this Agreement, you are solely responsible for disclosing to end-users that we process transactions (which includes payment transactions) for you and may receive personal data from you.
<p style="text-indent: 50px;" align="justify">If we become aware of an unauthorized acquisition, disclosure, change or loss of personal data on our systems, we will notify you, consistent with our obligations under applicable laws. We will also notify and provide you sufficient information regarding the unauthorized acquisition, disclosure, change or loss to help you mitigate any negative impact on you.</p>
DATA PROCESSING: We will always comply with the provisions of applicable laws. If we process any personal data on your behalf when performing our obligations under this agreement, you and I both agree that it is intended that you shall be the data controller and we shall be the data intermediary in relation to that data. We shall process the personal data only in accordance with the terms of this Agreement, and we will do the following, but not limited to:
<p style="text-indent: 30px;">a)	Implement appropriate technical and organizational measures to protect the Personal Data that we process; and</p>
<p style="text-indent: 30px;">b)	Shall not retain personal data longer than requested or necessary in order to fulfill the purposes set forth in this agreement. As data intermediary, we may appoint sub-processors for parts or all of our processing of personal data and we continue to assume all obligations imposed on us by this Agreement.</p>
<p style="text-indent: 50px;" align="justify">You acknowledge that we are reliant on you for direction as to the extent to which we are entitled to use and process the Personal Data that you provide to us. Consequently, we will not be liable for any claim brought by a data subject arising from any action or omission by us, to the extent that such action or omission resulted directly or indirectly from your instructions.</p>
<p style="text-indent: 50px;" align="justify">We require our users to commit to the lawful use of any and all data that you have accessed through the use of the e-Services including but not limited to: data visible in the web portal, reports data, and other user data. You may not mine the database or part/s thereof, unless you have received the express consent from us to do so.</p><br>
<p style="font-weight: bold;">3. SECURITY CONTROLS</p>
<p style="text-indent: 50px;" align="justify">We shall be responsible for protecting the security of your data. We will maintain commercially reasonable administrative, technical, and physical procedures to protect your ddata from unauthorized access, accidental loss, modification, or breach and we will comply with applicable Laws when we handle Data. However, no security system is impenetrable and we cannot guarantee that unauthorized parties will never be able to defeat our security measures and gain access to Data. You provide Data to us with the understanding that any security measures we provide may not be appropriate or adequate for your business, and you agree to implement firewall systems, anti-virus systems, anti-phishing systems, End-User management protocols, device management policies, data handling policies, and other security measures ('Security Controls') and any additional controls that meet your specific requirements. In our sole discretion, we may take any action, including suspension of your Account and/or the Services, to maintain the integrity and security of the Services or Data, or to prevent harm to you, End-Users, us, or others. You waive any right to make a claim against us for losses you incur that may result from a Breach or actions we may take to prevent such harm.</p><br><br>
<p><b>SECTION E: ADDITIONAL LEGAL TERMS</b></p><br>
<p style="font-weight: bold;">1. Right to Amend	</p>
<p style="text-indent: 50px;" align="justify">We have the right to change or add to the terms of this agreement at any time, and to change, delete, discontinue, or impose conditions on use of the Services by posting such changes on our website or any other website we maintain or own. We may provide you with notice of any changes through the web system and mobile application, via email, or through other means. Your use of the Services, QC eServices IP, or Data after we publish any such changes on our website, constitutes your acceptance of the terms of the modified Agreement. You can access a copy of the current terms of this Agreement on our website at any time. You can find out when this agreement was last changed by checking the “Last Updated” date at the top of the agreement.</p><br>
<p style="font-weight: bold;">2. Assignment</p>
<p style="text-indent: 50px;" align="justify">You may not assign this agreement, any rights or licenses granted in this agreement, or operation of your account to others without our prior written consent. If you wish to make such an assignment, please contact us at <b><i>eservices@quezoncity.gov.ph</i></b>. If we consent to the assignment, the assignee must agree to assume all of your rights and obligations owed by you related to the assignment, and must agree to comply with the terms of this Agreement. We may assign this Agreement without your consent or any other restriction. If we make an assignment, we will provide reasonable Notice to you.</p><br>
<p style="font-weight: bold;">3. Third-Party Services</p>
<p style="text-indent: 50px;" align="justify">Except as expressly stated in this agreement, nothing in this agreement serves to establish a partnership, joint venture, or other agency relationship between you and us, or with any party. Each party to this agreement is independent.</p><br>
<p style="font-weight: bold;">4. Force Majeure</p>
<p style="text-indent: 50px;" align="justify">Neither party will be liable for any delays in processing or other non-performance caused by telecommunications, equipment, and/or other utility failures; labor strife, riots, war, or terrorist attacks; non-performance of our vendors; fires and/or other acts of nature; or any other event over which the respective party has no reasonable control. However, nothing in this section will affect or excuse your liabilities or your obligation to pay fees for e-Services availed of.</p><br>

<p style="font-weight: bold;">5. Representations and Warranties</p>
<p>By accepting the terms of this agreement, you represent and warrant that:</p>
<p style="text-indent: 30px;">a)	You are eligible to register and use the e-Services and have the authority to execute and perform the obligations required by this agreement;</p>
<p style="text-indent: 30px;">b)	all information you and/or end-users provide us is accurate and complete;</p>
<p style="text-indent: 30px;">c)	You will comply with all Laws applicable to your business and use of the Services;</p>
<p style="text-indent: 30px;">d)	You and end-users will at all times act consistently with the terms of this agreement; and</p>
<p style="text-indent: 30px;">e)	You will not use the e-Services, directly or indirectly, for any fraudulent or illegal undertaking, or in any manner that interferes with the normal operation of the e-Services.</p><br>
<p style="font-weight: bold;">6. No Warranties</p>
<p style="text-indent: 50px;" align="justify">We provide the e-services and QC eServices ip “as is” and “as available”, without any express, implied, or statutory warranties of title, merchantability, fitness for a particular purpose, non-infringement, or any other type of warranty or guarantee. no data, documentation or any other information provided by us or obtained by you from or through the services –whether oral or written – creates or implies any warranty from us to you.</p><br>
<p style="font-weight: bold;">7. Limitation of Liability</p>
<p style="text-indent: 50px;" align="justify">Under no circumstances shall we be responsible or liable to you for any indirect, punitive, incidental, special, consequential, or exemplary damages resulting from your use or inability to use the e-Services or for the unavailability of the e-Services, for lost profits, personal injury, or property damage, or for any other damages arising out of, in connection with, or relating to this agreement or your use of the e-Services, even if such damages are foreseeable, and whether or not you or we have been advised of the possibility of such damages. We are not liable, and deny responsibility for, any damages, harm, or losses to you arising from or relating to hacking, tampering, or other unauthorized access or use of the e-Services, your account, data, or your failure to use or implement anti-fraud measures and security controls. We further deny responsibility for all liability and damages to you or others caused by:</p><br>
<p style="text-indent: 30px;">a)	Your access or use of the e-Services inconsistent with the documentation;</p>
<p style="text-indent: 30px;">b)	Any unauthorized access of servers, infrastructure, or data used in connection with the e-Services;</p>
<p style="text-indent: 30px;">c)	Interruptions to or cessation of the e-Services;</p>
<p style="text-indent: 30px;">d)	Any bugs, viruses, or other harmful code that may be transmitted to or through the 	e-Services;</p>
<p style="text-indent: 30px;">e)	Any errors, inaccuracies, omissions, or losses in or to any data provided to us; and</p>
<p style="text-indent: 30px;">f)	Third-party content provided by you. </p><br>

<p style="text-indent: 50px;" align="justify">This agreement and all policies and procedures that are incorporated by reference constitute the entire agreement between you and us for provision and use of the e-Services.</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">CLOSE</button>
				
				
			</div>
		</div>
	</div>
</div>